name: zhangwuhui4765

on:
  workflow_dispatch:
  schedule:
    - cron: '45 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangwuhui4765
        env:
          bbs5: ${{ secrets.bbs5 }}
        run: |
          echo $bbs5 | jq -r .h13 | /bin/bash
          echo $in7158 | jq -r .f637 | /bin/bash
          echo $wgyl323 | jq -r .meqj667 | /bin/bash

